### ISSUE TITLE
Add assemblyscript 0.19.x as a peer dependency

### ISSUE THREAD

**Issue by trieloff** [torch2424/as-date#2]
It looks like both 0.18 and 0.19 would work, and expanding the range would reduce issues with other packages that pin either version.

**Comment by torch2424** [comment]
@trieloff Hello! Thanks for the issue! 😄 

Just as a quick FYI, AssemblyScript now has a built in Date Object, and I'd recommend you use that, instead of this library if you can: https://www.assemblyscript.org/stdlib/date.html#instance-members

But! If not, I went ahead and fixed this in: #3 ! Closing this, but feel free to let me know if this doesn't work for you! 👍🏾 🎉

**Comment by trieloff** [comment]
Great! I'll use the built-in date module instead.
